appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: q23P8j4IOzGxIPuh2QDqtpPDYm3CaZzbFkhBJRawQCHPMqLJeuxRF4hvu06mJqqjpZ/E44+l1s1LGBT0V75YBdQrEvk1LpaQVsWAEp2iJqUKYHZxbhRIxJjLHYQd94/QXiV/knnfJjjH/Uu5fHQ0+dEUsLosy7lNhmGYicyA2hsLfFoHK3WolgKVCfTMOaRZeDTknqUk8tkrmenYLOHd/64px9bEpxhm+beEw9XmslcKPOpQgOCG8qG7GBnYEQTT0rcI6F05WCfXtMhk5MdpKWSzEoUf5g50dVvOnoXaa71eVn2wUL+aQ/OjL8BOu5OHGUEuy0SeFwQ+ovYL9a+xXmlLZAeHFsyYtlfeQKQoQt2N1LhXwRNbMls1Yu6JYystWIy93t+owQd9LC4AmSRfN2iv+fh7QJOk+M8NcaPDVEhUzUYMuWVbNukWrVpiNG4h7xU5ZIpNhFXT54BJae4C0E8SKaNbACa6umxo+oCLcFPeGhbIdNAx5elgTZflfxxwgwWCft61HtePoAUWXuau9ejwlt64ZrdNI3pD0ZY0malyt8URzSZvaDDLcOZMArsrEb4lfsQ3Qh7b2KbCWZQVsdwr6BfJr/c01/7bTEl2jVOpc5diyrarwV8f8X0lEbjb5MFThdQ8BBmfr6e2MdmF0aoUQbqVIOJ+ZnQ5rzxhi9s=}
provider:
  win: azure
